- include/lcp-catlist.php
Fixed the 'starting_with' option no longer show inherit or draft post/pages like before !
> Starting With Fixed

- include/lcp-catlistdisplayer.php
> Fix error causing call to undefined method

- include/lcp-catlist.php
- readme.txt
Add excerpt=full to allow either full explicit excerpt or use
<?--more--> to define where the excerpt ends.
> Add excerpt=full.

- include/lcp-catlist.php
- include/lcp-catlistdisplayer.php
Revert commit eb3699a8fbe4c0043655ca6ef885ecd3594c1bda (which itself reverted the last attempt at fixing "the loop") and add back in and fix the missing function used by templates.
> Sophist fix the loop 2nd attempt

- include/lcp-catlistdisplayer.php
- list-category-posts.php
- readme.txt
> New feature: link to post wrapper for the post date

- list-category-posts.php
> adds a default value to numberposts on plugin activation

- include/lcp-catlistdisplayer.php
Solution to the issue here: https://github.com/picandocodigo/List-Category-Posts/issues/201 .
This is my first contribution to the project. Not sure what information I should post.
> solved issue 201: missing assignment for  and  if non-empty or not null

- include/lcp-catlistdisplayer.php
- list-category-posts.php
PR for issue #217 
This was a quick addition. I'd like to help out with this plugin. Please let me know if anything else should be changed in the repo (documentation?).
> use posts' tags to set classes

- .gitignore
- Vagrantfile
- bootstrap.sh
#265 
Updated Vagrant machine to:
* ubuntu/xenial64
* PHP 7.0
* MySQL 5.7
Test website works, phpunit passes
I tried the shortcode with many different parameters and got no PHP warnings or errors so I assume it is all valid PHP 7.0
> Update Vagrant machine

- include/lcp-paginator.php
Sorry for putting this bug in your plugin's code... This fixes it.
> Fix pagination bug

- include/lcp-paginator.php
- list-category-posts.php
- readme.txt
- tests/lcppaginator/test-getInstance.php
- tests/lcppaginator/test-getPagination.php
This is #279 but with one fix.
My unit test noticed a tiny bug where pagination link classes were added inappropriately when using many instances of pagination on same page :wink: All because of Singleton (which I personally don't like...)
Now it should be ok.
> Paginator tests

- include/lcp-parameters.php
- include/lcp-utils.php
- readme.txt
- tests/lcputils/test-lcpOrders.php
ID for widget ordering
https://wordpress.org/support/topic/adding-orderby-id/
`currenttags=all` for AND relationship
https://wordpress.org/support/topic/can-currenttagsyes-be-set-to-a-and-relationship/
> Small feature requests

- include/lcp-catlist.php
- include/lcp-paginator.php
- list-category-posts.php
- tests/lcppaginator/test-getPagination.php
Added `pagination_padding` parameter and tests for dynamic pagination.
Fixed indentation in lcp-paginator.php and in the tests.
Fixes #83
> Dynamic pagination

- include/lcp-thumbnail.php
in lcp-thumbnail.php - will use the post title as an alt tag for the thumblist images
> print post title as alt tag for accessibility

- .travis.yml
- bin/install-wp-tests.sh
> Fix travis

- include/lcp-catlist.php
> Don't display empty custom fields. Fixes #409

- include/lcp-category.php
- include/lcp-catlist.php
- tests/lcpcategory/test-getLcpCategory.php
- tests/lcpcategory/test-withId.php
- tests/lcpcategory/test-withName.php
> Improve LcpCategory

- bin/bootstrap.sh
This is now working for me on Windows. Needs to be run as admin (that's already in the readme).
> Fix vagrant setup on Windows

- README.md
- list-category-posts.php
- readme.txt
@zymeth25 working on the changelog and version bump, did I miss anything? Also crediting you more for the work you've been doing :clap: :clap: 
Thank you!
> Update READMEs and bump version

- include/lcp-catlist.php
- include/lcp-catlistdisplayer.php
- include/lcp-wrapper.php
- tests/catlistdisplayer/test-display.php
- tests/catlistdisplayer/test-getPostTitle.php
@picandocodigo perhaps you can use this to fix #350 ?
I will write a few tests for this later so that it's finished.
> Refactor HTML generation

- include/lcp-catlist.php
Somehow didn't notice it ealier 😆 
https://wordpress.org/support/topic/display_idyes-not-showing-id-in-preview/
> Fix display_id bug

- .github/workflows/master.yml
> Debug master.yml

- README.md
- readme.txt
Hope I haven't forgotten anything important 😆
> Update gh username

- README.md
- list-category-posts.php
- readme.txt
Klemens, let me know if I missed something!
> Updates docs and bumps version to 0.84

- include/lcp-widget.php
https://wordpress.org/support/topic/undefined-index-error-66/#post-14387787
> Fix includeposts undefinded index in older widgets

- include/lcp-catlist.php
- include/lcp-catlistdisplayer.php
- tests/catlistdisplayer/test-getCategoryCount.php
- tests/catlistdisplayer/test-getCategoryDescription.php
- tests/catlistdisplayer/test-getCategoryLink.php
- tests/catlistdisplayer/test-getConditionalTitle.php
- tests/catlistdisplayer/test-getMorelink.php
- tests/catlistdisplayer/test-getNoPostsText.php
- tests/catlistdisplayer/test-getPagination.php
I am going to add integration tests for all displayer methods since they are the main interface for displaying stuff. If I find bugs while doing this I will fix them, too. 
So I will hack some tests every now and then and once everything is covered will merge this in.
> Displayer integration tests

- include/lcp-widget.php
This may fix a compatibility issue with certain versions
of PHP 7.4
https://wordpress.org/support/topic/fatal-error-3888/
> Hotfix for strange compatibility issues with PHP

- include/lcp-catlistdisplayer.php
- list-category-posts.php
- tests/catlistdisplayer/test-getPostTitle.php
> Customise link for current post

- include/lcp-parameters.php
- list-category-posts.php
- tests/lcpparameters/test-getQueryParams.php
Resolves https://wordpress.org/support/topic/exempt-sticky-posts/
Fixes #342
> Add ignore_sticky_posts

- include/lcp-widget.php
Fixes PHP Warnings reported in https://wordpress.org/support/topic/bug-php-8-1/
> Hotfix widget

- include/lcp-catlist.php
- include/lcp-catlistdisplayer.php
- include/lcp-paginator.php
- include/lcp-thumbnail.php
- include/lcp-wrapper.php
- tests/lcppaginator/test-getPagination.php
This PR implements data escaping following official WP docs
https://developer.wordpress.org/apis/security/escaping/
> Implement WordPress style data escaping

- include/lcp-catlist.php
- include/lcp-catlistdisplayer.php
- tests/lcpcategory/test-currentCategory.php
> Fix PHP 8.2 deprecation notices

- README.md
- readme.txt
Added the repo in [Codeberg](https://codeberg.org/picandocodigo/list-category-posts/),
> Updates readme.txt
