picandocodigo/List-Category-Posts

- include/lcp-catlist.php
- readme.txt
Enable content=full in addition to content=yes.
content=full ignores the [more] text break and shows the content of the article in full.
This allows for e.g.
```
[catlist numberposts=1 content=full]
[catlist numberposts=4 offset=1 content=yes]
```
to show the first post in full, and following posts up to the [more] point.
> Add content=full option

- include/lcp-catlistdisplayer.php
- list_cat_posts.php
- readme.txt
The new attribute 'no_post_titles' is added to shortcode 'catlist',
which can have two values: 'yes' or 'no'. 'no' is the default value,
which will lead to the normal shortcode behavior as in the original
version of the plugin. 'yes' will omit the titles of the posts in
the post list.
This new option is intended for use with 'content=yes', in which
case it will basically include the post text directly without having
a separate title per entry. This allows for building bibliographies
with one literature entry per post and displaying them as lists, as
done for example on the test page
http://thomasweise.apps-1and1.net/publications/all
(which will eventually be moved elsewhere).
The modification of the plugin is really minimal. Besides adding
the new attribute with default value 'no' in file …
> New Attribute 'no_post_titles' for Shortocode 'catlist'

- include/lcp-widget-form.php
- include/lcp-widget.php
With this update user-defined image-sizes (i.e. custom sizes, defined in
functions.php of your theme) are considered within the selection of
thumbnail-sizes within the widget's settings.
Also, it sets the name of the selected thumbnail-size correctly after
settings have been saved and the page is reloaded.
Signed-off-by: Stefan Nussbaumer <st9fan@gmail.com>
> add custom image sizes to the list of selectable image sizes

- include/lcp-catlistdisplayer.php
When using one of the pagination buttons for the second time, the plugin
will generate URLs containing the substring '?&' which in turn
potentially confuses later rewrite rules. The applies WA will check the
generated URLs in the pagination and replace '?&' by a simple '?'.
> Workaround to prevent '?&' to appear in URLs

- include/lcp-widget-form.php
The displayed string has the same case that can be found later in the file ('Modified Date' with an upper 'd' and not 'Modified date').
As this string was used before, its translation already exists.
> Allow to order by the modified date in the widget

- include/lcp-thumbnail.php
After a lot more testing, I think this is ready to go... Live examples at www.cbtownandcountry.com/redlands-office.
I've added code so that if thumbnail is requested but there isn't a featured image, it will grab the first image in the post.
This is extremely helpful to ensure a consistent look and feel in the category post listing, especially in cases where there is a mix of posts with featured images vs posts that link out to other sites for an image in the post.
This now respects the thumbnail_class parameter if one is passed otherwise the class of lcp_thumbnail is applied to the img tag.
> Expanded support for Thumbnail in ListCat

- include/lcp-catlist.php
This commit fixes how the child_category parameter is processed.
I found that the current implementation did not work correctly for me. It seemed that the branch checking for whether child_categories is set to no or false never was taken even though the parameter was set so. With these changes the if-branch is taken correctly.
Please note: There seems to be some issue with the category__in argument used, which (on my site) causes no entries to be shown at all. :(
> Handle child_categories flag correctly

- include/lcp-thumbnail.php
Seems if we are are going through the trouble of adding the thumbnail, we should probably be thorough and add an Alt tag to the image. Using the title of the article that is being linked to is probably the best course of action. Yes, we have it in the title for the link around the image but the SEO value is probably just as strong in the Alt Tag (to be picked up by Google Images, etc).
No?
> Added Alt Tag to thumbnail

- include/lcp-widget.php
This fixes the error on WordPress 4.5.2 / PHP 7 (or below, needs testing) that says: "PHP Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP"
**Note:** Disregard line 118 change, as it was added by GitHub.
> Update lcp-widget.php for PHP 7 compatibility

- include/lcp-widget.php
This squelches an 'undefined index' PHP Notice that appears for
widgets that were last saved before upgrading to 0.71.1.
Fixes #231.
> Make sure the tags_as_class instance variable is defined

- include/lcp-parameters.php
The current custom taxonomy implementation only supports the "or" relationship when using multiple terms. This change adds support for the "and" relationship by using the plus sign instead of the comma. Example usage: [catlist taxonomy='topic' terms='topic1+topic2']
> Custom taxonomy terms with "and" relationship

- include/lcp-catlistdisplayer.php
Quick fix for a bug reported [here](https://wordpress.org/support/topic/pagination-with-template/)
> Fix pagination for templates

- include/lcp-parameters.php
- readme.txt
#261 was closed but the issue is unresolved so I devised this quick fix. Since it was discussed in that thread I will skip the description here.
Instead of using simple parameters like `meta_key` I'm passing `meta_query`, an array of arrays. This allows for all sorts of magic that WP_Meta_Query has.
> Refactor custom fields

- include/lcp-paginator.php
- include/lcp-widget.php
- list-category-posts.php
Two fixes in this PR:
* c5a0b27 didn't fully work, if there is no `pagination=yes` but backend option is set to `true`, no pagination will be displayed right now. I fixed the logic in `lcp-paginator.php`
* The wiki says `pagination` can be set to `yes` or `no`, but the code looks for `yes` or `false`. I fixed this for consistency
> Fix pagination parameter/option

- include/lcp-catlist.php
- include/lcp-paginator.php
- include/lcp-utils.php
The `check_pagination` method in `CatList` is outdated, it doesn't check if pagination is on in a proper way, it only looks if the parameter exists but doesn't care about its value, it also disregards backend options.
I noticed this while refactoring the code for less repetition. My refactoring fixes the above problem:
* I moved the `show_pagination` method of `LcpPaginator` to `LcpUtils` to make it reusable
* then I changed the `check_pagination` method to perform a proper check using `LcpUtils`
* I also fixed indentation in `LcpUtils` for consistency
> Refactor pagination check

- include/lcp-parameters.php
Fixes [this issue](https://wordpress.org/support/topic/starting_with-not-work/)
> starting_with support for utf8mb4 charset

- include/lcp-category.php
- include/lcp-catlistdisplayer.php
- include/lcp-widget.php
- tests/lcpcategory/test-currentCategory.php
This is the result of these two threads:
* [Thread 1](https://wordpress.org/support/topic/categorypageyes-is-not-detecting-the-correct-category-sometimes/)
* [Thread 2](https://wordpress.org/support/topic/catlink-on-title-field-of-widget-does-not-work/)
Many thanks to infinityx78 for suggestions!
Since this is all about 'current category' I'm throwing in initial tests for LcpCategory.
Fixes #155
> Fixes for widget, tests for current_category

- include/lcp-catlist.php
Issue reported and fix suggested by puddleglum on WP Support Forum.
https://wordpress.org/support/topic/bug-this-get_authorpost-malformed-markup/
(Why can't people submit a PR themselves if they know the fix???)
> Fix author_posts_link markup

- include/lcp-parameters.php
Issue reported by stefanr on WP Support Forum.
https://wordpress.org/support/topic/after-not-creating-date-query/
He was correct in that thread, `after` and `before` don't work at all. But I like my solution more than his 😛
> Fix date query

- include/lcp-widget.php
create_function is deprecated as of PHP 7.2.0
Not using an anonymous function because as of now it breaks PHPUnit.
Fixes [this issue](https://wordpress.org/support/topic/php-deprecated-function-create_function-is-deprecated-2/)
> Use regular function instead of create_function

- include/lcp-parameters.php
https://wordpress.org/support/topic/fatal-error-after-0-76-update/
So maybe better release this hotfix and add a deprecation warning in the changelog that we will be dropping support for pre 5.4 because those old versions are really dumb with arrays.
> Restore PHP < 5.4 compatibility

- include/lcp-catlist.php
In some rare cases wp_reset_query fails to reset global `$post`
to its initial value. This manual reset ensures the plugin leaves
the main query in a clean state regardless of circumstances
https://wordpress.org/support/topic/your-plugin-has-a-crazy-bug-conflict-with-elementor/#post-10145793
Fixes #320
> Improve restoring main query

- include/lcp-parameters.php
`[catlist before=today]`
When I wanted to create a custom archive page for one of my projects, I hardcoded the query because neither there was a way to pass a dynamic date argument nor an option to display past posts through catlist. By this change, the plugin will get today's date dynamically and display only old posts. I believe this small change will be life saver for others too :)
> Display all posts except today's

- include/lcp-catlist.php
- include/lcp-paginator.php
- list-category-posts.php
- tests/lcppaginator/test-getPagination.php
Pagination links are automatically appended with bookmarks to the list they are part of, i.e. lcp_instance. While this is desirable by many users, it can cause a real mess in many (badly written 😉 ) themes and plugins. So I'm proposing to introduce `pagination_bookmarks` shortcode parameter. If present and set to `no` the plugin won't append bookmarks to pagination URLs.
Default (current) example link
`http://example.org?lcp_page0=2#lcp_instance_0`
With `pagination_bookmarks=no`
`http://example.org?lcp_page0=2`
Fixes #225, fixes #291
There were also many support questions on WP Forum, like [this one](https://wordpress.org/support/topic/pagination-links-scroll-to-top-of-same-page/) or [one from today](https://wordpress.org/support/topic/issue-with-pagination-and-loading-slider-revolution/)
> Parametrise bookmarks in pagination links

- include/lcp-parameters.php
Right now instead of `$args`, `$params` are passed to `lcp_excluded_tags`. This small bug means that if a user specifies `exclude_tags` shortcode parameter, two things happen:
1. Any `$args` set and parsed above line 142 of lcp-parameters.php will be ignored, e.g. `excludeposts`, `before_year` etc.
2. A full array of  raw LCP parameters will be passed to `WP_Query`
This is fixed in this PR.
Fixes https://wordpress.org/support/topic/excludepoststhis-not-working/
> Fix args overwrite bug in exlude_tags

- include/lcp-catlistdisplayer.php
CatListDisplayer::build_output should display the conditional
title before the list wrapper. This is already correctly
implemented in the default template file.
https://wordpress.org/support/topic/bug-h3-inside-ul-tag/
> Move conditional title out of the list wrapper

- include/lcp-category.php
- include/lcp-widget.php
- readme.txt
- tests/lcpcategory/test-currentCategory.php
- tests/lcppaginator/test-getPagination.php
Fixes #69 
This is a follow up on #292 , according to #69, when using `categorypage=yes` and there is no current category (when we are not on a single page or category archive) no posts will be displayed. Once I fixed this I was able to finish writing test cases for current category.
In the current version of the plugin if we are, say, on our home page or date archive and have LCP `categorypage=yes` in our widget, the plugin will read the category of the **last** post of current loop as current category. If we add another LCP after the first one, it will read the **first** post of current loop as current cateogory. So we then have two LCP instances showing different categories :wink:
And when we are on a single page, we will get posts from all categories.
This PR changes it so that in all …
> Current category

- doc/FAQ.md
- include/lcp-category.php
- include/lcp-catlist.php
- tests/lcpcategory/test-currentCategory.php
Perhaps also worth adding to 1.0. Contains features requested on support forums.
Changed:
* `categorypage=yes` will get *all* post's categories with OR relationship
Added:
* `categorypage=all` for AND relationship
* `categorypage=other` to get all categories except current categories (with OR relationship, of course)
> Categorypage final polishing

- .gitignore
- .travis.yml
- README.md
- Vagrantfile
- bin/bootstrap.sh
- bin/install-wp-tests.sh
Changed:
* Vagrant:
* ubuntu/xenial64 -> ubuntu/bionic64
* PHP 7.0 -> PHP 7.2
* Instead of fetching latest PHPUnit, fetch PHPUnit 6 because later versions are not supported by WordPress
* Travis:
* PHP 7.0 -> PHP 7.2
* Conditionally install and run PHPUnit 6 when running PHP 7.2 because Travis would use PHPUnit 7 which is not supported by WordPress
* Tests setup:
* `WP_TESTS_DIR` now points to the same directory in all bash scripts.
* moved `bootstrap.sh` to `bin/bootstrap.sh`
Added:
* Vagrant:
* `vagrant up` will create a `wordpress` directory and sync it with WP instance on the Vagrant box. This will make editing theme files and custom templates easier.
* `php-gd` package, in case someone wanted to do image resizing for thumbnails
* `WP_DEBUG` and `WP_DEBUG_LOG`, both set to `true`
* a …
> Update testing environment

- include/lcp-category.php
When posts are displayed in the Loop, for example on the home page or archive, LCP shortcodes using `categorypage` in those posts will show no links. I introduced this bug in #327 because I completely forgot about this use case 😉 
Thanks @Coxworld for reporting this.
Fixes #358
> Fix current category for posts displayed in the loop.

- include/lcp-catlist.php
- include/lcp-catlistdisplayer.php
- include/lcp-wrapper.php
- list-category-posts.php
- tests/catlistdisplayer/test-display.php
- tests/lcpwrapper/test-getInstance.php
- tests/lcpwrapper/test-wrap.php
I only wanted to refactor `CatListDisplayer` and create `LcpWrapper` but it quickly turned out that to do it properly I have to change many other files...
Anyway, I moved wrapping with tags and classes to `LcpWrapper`. This PR alters many lines of code but in most cases for clarity and ease of use, not much changes in how the plugin works, except:
* `something_tag` and `something_class` parameters now work in all template functions, they take precedence over arguments
* some template functions now have default parameter values to match simple shortcode bahaviour, e. g. `get_category_link($tag = 'strong', $css_class = null)`
* I added `thumbnail_tag` because template function already had this feature but default build function didn't
Other thigs that don't change how things work but are …
> Refactor CatListDisplayer, add some tests

- include/lcp-parameters.php
https://wordpress.org/support/topic/notice-undefined-variable-params/#post-13054301
> Fix order bug after refactor

- include/lcp-templater.php
When I was refactoring things in #411 I forgot that the widget admin panel scans for templates.
Re-added an `is_dir` check so that PHP doesn't complain about non existent directories.
> Fix PHP warnings caused by widget back end

- include/lcp-catlist.php
This was fixed many years ago in #145 but later the code was refactored out and the bug rose its ugly head again 🤣 
Fixes #439
> Fix posts_where filter not being properly removed when using starting_with

- include/lcp-catlist.php
Pull request to ensure that if the parameter "excerpt=full" is set, then any excerpt is sent through the normal excerpt filters (i.e. in a consistent manner as for "excerpt=yes").
> Update lcp-catlist.php to pass excerpts=full through filters

- .distignore
- .github/workflows/deploy.yml
Hi @picandocodigo, I use[ this action](https://github.com/10up/action-wordpress-plugin-deploy) in the GUI plugin and I like how it simplifies deployment. Maybe you will find it helpful too 😃 
The `.distignore` lists files to exclude during deployment, I think I got it right but do have another look :wink:
The action automatically deploys to WP repository when a new tag is pushed. The tag in git can include a leading `v` and the action will strip it and create a direcory in `/tags` without it.
Optionally, you can also create a `.wordpress-org` directory and the action will copy its contents to svn `/assets`.
All you need to do to make it work is to add required secrets to the repository as described [in the docs](https://github.com/10up/action-wordpress-plugin-deploy#required-secrets).
> Add deploy to WP action

- templates/default.php
Currently the default tag for `content=yes` is `p` which produces invalid HTML because a paragraph element can only have inline children.
https://wordpress.org/support/topic/default-template-wraps-content-with-p/
> Change default content tag to div

- include/lcp-catlist.php
- include/lcp-catlistdisplayer.php
- list-category-posts.php
- templates/default.php
In addition to neccessary method updates and new shortcodes:
`category_description_tag` and `category_description_class`,
the `category_description()` function has been replaced with
the `get_term_field(`) function because the former automatically
wrapped output in `<p>` tags. The default `<p>` tag has been retained
by updating the default LCP template.
Fixes #364
> Add category_description styling

- include/lcp-parameters.php
- include/lcp-widget-form.php
- include/lcp-widget.php
- list-category-posts.php
This PR adds a `includeposts` parameter that allows to list selected posts/pages by ID. Also adds the corresponding option in the widget form.
Example usage:
[catlist post_type="page" includeposts="2,97" content="full"]
> Allow to include posts by ID (resolve #310)

- include/lcp-paginator.php
- list-category-posts.php
The plugin should follow WP best practices and include hooks to allow developers to interact with it.
First hooks are:
* `shortcode_atts_catlist` - a built in WP hook [documented here](https://developer.wordpress.org/reference/hooks/shortcode_atts_shortcode/).
* `lcp_pagination_html` - a custom filter hook, will be, currently, the only way to alter pagination html.
> Making the plugin extensible - first hooks.

- include/lcp-meta-query.php
- list-category-posts.php
- customfield_orderby - You can order the posts by a custom field. For example: [catlist numberposts=-1 customfield_orderby=Mood order=desc] will list all the posts with a "Mood" custom field. This parameter can be used toghether with customfield_name and customfield_value, you can use those parameters to select posts and then customfield_orderby to sort by this or another custom field. For other than alphabetical sorting, you can use customfield_type parameter (NUMERIC, BINARY, CHAR, DATE, DATETIME, DECIMAL, SIGNED, TIME, UNSIGNED). Remember the default order is descending, more on order:
> #452 support customfield data type

- .github/workflows/master.yml
- .gitignore
- Vagrantfile
- bin/bootstrap.sh
- phpunit.xml
- tests/bootstrap.php
As of September 2021 WordPress 5.9 and above require
PHPUnit-Polyfills for WordPress PHP Test Suite to work.
https://make.wordpress.org/core/2021/09/27/changes-to-the-wordpress-core-php-test-suite/
> Add PHPUnit-Polyfills to CI setup

- include/lcp-catlist.php
- include/lcp-utils.php
- include/lcp-wrapper.php
- tests/lcpwrapper/test-wrap.php
https://wordpress.org/support/topic/target-multiple-css-elements/#post-15307010
When trying to apply more than one class, the classes where glued together without a separator.
> Fix multiple CSS classes

- include/lcp-catlistdisplayer.php
- include/lcp-parameters.php
- list-category-posts.php
By default when using `name` or `cat` WP_Query will get
all posts matching given categories but order them normally,
including sticky posts. This change allows users to put sticky
posts at the top in this kind of queries.
Fixes #423
> Allow customisation of sticky posts for categories

- include/lcp-parameters.php
- include/lcp-taxonomies.php
- list-category-posts.php
- tests/lcpparameters/test-createTaxQuery.php
Resolves #293 
Usage: `[catlist taxonomy="mouse" currentterms=yes]` or `[catlist taxonomy="mouse" currentterms=all]`
Similar to `currenttags`.
> Current terms

- include/lcp-category.php
- include/lcp-catlist.php
- list-category-posts.php
- tests/lcpcategory/test-getLcpCategory.php
Allow filtering by posts' main/primary category only. Supports Yoast's "primary category" feature; falls back to first assigned category.
Usage `[catlist name="Foo" main_cat_only=yes]`
Resolves #449
> Add filtering by main category only

- include/lcp-thumbnail.php
Refactoring in 1e97354 resulted in youtube thumbnails not working at all. This commmit fixes the `check_youtube_thumbnail` method but that method's code is quite old and may not work as intended. Needs further testing.
> Fix refactor bug in check_youtube_thumbnail()

- Vagrantfile
- bin/bootstrap.sh
Updated PHP to 8.1 and PHPUnit to 9.
Depracation warnings in the provisioning script can be safely ignored.
Deprecation warnings when running PHPUnit and probably more when manually testing the plugin, should be gradually fixed.
> Upgrade Vagrant machine

- include/lcp-catlistdisplayer.php
- include/lcp-wrapper.php
- list-category-posts.php
- readme.txt
Bumps version to 0.90.2
@klemens-st Another way to trigger an XSS with `script` was reported for different fields. As we've talked before, the vulnerabilites are present when WordPress has already been compromised, since the malintentioned user would need permision to publish content on the system to trigger them. But if it helps keeping a site safer, then why not... :shrug:
Ideally I think it's up to the users to use or not use `<script>` with the plugin, so eventually we *could* make this optional (warning the users they should really know what they're doing if they want to allow it).  But I think it's also ok not to support the `script` tag.
I think this is the best place in the code to remove support for `<script>` since it's the function `wrap` uses, and the times `to_html` is used …
> Updates fix for stored cross-site scripting from 0.90.0, now applied to all tags.

- .github/workflows/master.yml
Since Ubuntu 24.04 Github worker svn is no longer included and needs to be setup manually.
> Add Subversion instllation step to CI workflows

- include/lcp-wrapper.php
- list-category-posts.php
- readme.txt
- tests/lcpwrapper/test-wrap.php
@picandocodigo I realised the fix from #526 works well when someone uses `excerpt_tag=script` but if someone tries `excerpt_tag="s(cript"` the fix is ineffective, because `to_html` receives this value, escapes it with `tag_escape` so in the end it becomes `script`.
This small change prevents that.
> Harden xss security fix

- include/lcp-templater.php
- readme.txt
This should remove the possibilty of local file inclussion by not allowing `../` in the template parameter. 
However, the plugin still allows including php files from the theme's directory. If an attacker had access to the server's file system, they could upload or create an exploit in the current theme directory. If they also have access to the dashboard and permissions to write/edit posts and use the plugin, they could still include a bad file by using the template parameter.
Like previously reported vulnerabilities, **to take advantage of this vulnerability, the whole system needs to have already been compromised**.
We can still make the plugin more secure, but I'm not sure if this fix would be enough to consider this vulnerability fixed. The alternative would be to completely remove …
> CVE-2025-47636
